name: CI Test Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always


jobs:
  run-security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run code audit
        run: |
          cargo install cargo-audit
          cargo audit
      - name: Check style
        run: |
          rustup toolchain install nightly
          rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly, beta]
    steps:
    - uses: actions/checkout@v2
      with:
        rust-version: ${{ matrix.rust }}
    - name: Build
      run: cargo build --tests --verbose
    - name: Run tests
      run: cargo test --verbose